[project]
name = "fast-api-endpoints"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standards]>=0.128.0",
    "uvicorn>=0.40.0",
]
